version: 2.1

# reusable 'executor' object for jobs
executors:
  go:
    docker:
      - image: docker.mirror.hashicorp.services/circleci/golang:1.16
    environment:
      - TEST_RESULTS: /tmp/test-results # path to where test results are saved

jobs:
  go-fmt-and-vet:
    executor: go
    steps:
      - checkout
      - run: go mod download

      # check go fmt output because it does not report non-zero when there are fmt changes
      - run:
          name: check go fmt
          command: |
            files=$(go fmt ./...)
            if [ -n "$files" ]; then
              echo "The following file(s) do not conform to go fmt:"
              echo "$files"
              exit 1
            fi
      - run: go vet ./...

  go-tests:
    executor: go
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS

      # Restore go module cache if there is one
      - restore_cache:
          keys:
            - memberlist-modcache-v1-{{ checksum "go.mod" }}

      # run go tests with gotestsum
      - run: |
          gotestsum --format=short-verbose --junitfile $TEST_RESULTS/gotestsum-report.xml -- -race
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results

workflows:
  version: 2
  go-tests:
    jobs:
      - go-fmt-and-vet
      - go-tests:
          requires:
            - go-fmt-and-vet
